apiVersion: v1
data:
  secretkey: cVBqUjU1c3RQdFpJTWxLUUdWM2NtVktFQWNwL2Y5M0EyU2g1cnBEQWRybzMraStJb1V4S290bkh4SHU1NDhoKwp2cGpyMXJxdnFUUHFkVDJaOW5YT0FYVUFrdE9tRGhQZEMwQSt0MHRGUUM1MHlwMk1NN2lENGdJZTVPZzNxaEFGCjRpUFBDbmVIa2NZbisxaERZemNMcU9mT3dtTkkwZmRpZU5UcFV0TVk4Sms9
kind: Secret
metadata:
  creationTimestamp: null
  name: memberlist
  namespace: metallb-system
