apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb
spec:
  addresses:
  - 203.250.33.75-203.250.33.75
  - 203.250.33.83-203.250.33.85

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-network-l2
  namespace: metallb
spec:
  ipAddressPools:
  - first-pool
