apiVersion: metallb.io/v1alpha1
kind: AddressPool
metadata:
  namespace: metallb
  name: doc-example
spec:
  protocol: layer2
  addresses:
  - 203.250.33.75-203.250.33.75
  - 203.250.33.83-203.250.33.85
