apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 203.250.33.83-203.250.33.83
  - 203.250.33.85-203.250.33.87
  - 203.250.33.90-203.250.33.90
  - 203.250.34.140-203.250.34.140
  - 203.250.34.143-203.250.34.146


---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-network-l2
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
